### ISSUE TITLE
Jellyfin runs, but can't access localhost

### ISSUE THREAD

**Issue by JasonFrovich** [jellyfin/jellyfin-server-macos#25]
So I can see the Jellyfin menu item. It won't load localhost. I am unable to find the log files. Any idea what's going on?
Im running Jellyfin for macOS 10.5.2 - Phoenix Edition Edit
Jellyfin server is showing in activity monitor.

Following the steps posted in https://www.reddit.com/r/jellyfin/comments/dgovbc/calling_all_macos_users/
little debugging:

If you open the Activity Monitor, is “jellyfin” running?( No , only the server, jellyfin
shows up then disappears.)
If so, select it and click force quit, and quit the menu bar app as well (done)
try again, )I have tried several times)
if it still doesn’t work, use the menu bar icon to “Show Logs” (this does nothing, I am unable to find the log files)
Grab the most recent log, open it in TextEdit( see above comment)
Remove any information you don’t want me to see (like change names or anything)
Grab the piece from the last startup attempt
Post it here, or somewhere else like Pastebin

Hardware Overview:
Model Name: iMac
Model Identifier: iMac17,1
Processor Name: Intel Core i5
Processor Speed: 3.2 GHz
Number of Processors: 1
Total Number of Cores: 4
L2 Cache (per Core): 256 KB
L3 Cache: 6 MB
Memory: 24 GB
Boot ROM Version: 176.0.0.0.0

Here are the console logs
```
default 12:15:01.720220 -0500 ReportCrash Saved crash report for jellyfin[92980] version 0 to jellyfin_2020-04-15-121501_Jasons-iMac-2015.crash
default 12:15:01.722507 -0500 ReportCrash Removing excessive log: jellyfin_2020-04-15-030044_Jasons-iMac-2015.crash
default 12:15:02.802957 -0500 Jellyfin Server Launching Jellyfin Server
default 12:15:03.095939 -0500 Jellyfin Server Jellyfin Server terminated (exit code 6)
default 12:15:03.096021 -0500 Jellyfin Server Delaying Jellyfin startup by 5.0 s
default 12:15:04.931648 -0500 ReportCrash Saved crash report for jellyfin[92986] version 0 to jellyfin_2020-04-15-121504_Jasons-iMac-2015.crash
default 12:15:04.933383 -0500 ReportCrash Removing excessive log: jellyfin_2020-04-15-030106_Jasons-iMac-2015.crash
default 12:15:08.096146 -0500 Jellyfin Server Launching Jellyfin Server
default 12:15:08.581714 -0500 Jellyfin Server Jellyfin Server terminated (exit code 6)
default 12:15:08.581788 -0500 Jellyfin Server Delaying Jellyfin startup by 5.0 s
default 12:15:10.123467 -0500 ReportCrash Saved crash report for jellyfin[92987] version 0 to jellyfin_2020-04-15-121510_Jasons-iMac-2015.crash
default 12:15:10.125161 -0500 ReportCrash Removing excessive log: jellyfin_2020-04-15-025942_Jasons-iMac-2015.crash
default 12:15:13.581889 -0500 Jellyfin Server Launching Jellyfin Server
default 12:15:13.953296 -0500 Jellyfin Server Jellyfin Server terminated (exit code 6)
default 12:15:13.953377 -0500 Jellyfin Server Delaying Jellyfin startup by 5.0 s
default 12:15:15.537092 -0500 ReportCrash Saved crash report for jellyfin[92988] version 0 to jellyfin_2020-04-15-121515_Jasons-iMac-2015.crash
default 12:15:15.538706 -0500 ReportCrash Removing excessive log: jellyfin_2020-04-15-121515_Jasons-iMac-2015.crash
default 12:15:18.953578 -0500 Jellyfin Server Launching Jellyfin Server
default 12:15:19.156604 -0500 Jellyfin Server Jellyfin Server terminated (exit code 6)
default 12:15:19.156706 -0500 Jellyfin Server Delaying Jellyfin startup by 5.0 s
default 12:15:20.533405 -0500 ReportCrash Saved crash report for jellyfin[92989] version 0 to jellyfin_2020-04-15-121520_Jasons-iMac-2015.crash
default 12:15:20.536090 -0500 ReportCrash Removing excessive
```

**Comment by JasonFrovich** [comment]
Ok so what do I use to run jellyfin? the file I mention of the jellyfin exactable in the folder download from the main site? Cause that seems to work, I can get local host and to the Welcome to Jellyfin! setup. This page says to use the App
https://jellyfin.org/docs/general/administration/installing.html

Very confusing.

**Comment by evnb** [comment]
I'm having the same issue. (Late 2014 mac mini with macOS 10.15.1 here.) 

I first tried Jellyfin portable 10.5.4 as [the site's stable macos download button links to it.](https://repo.jellyfin.org/releases/server/macos/stable/) That seemed to sort of work but it was pretty confusing and GateKeeper did NOT like all the dependencies (I manually rightclicked to open each dependency, then clicked "still open". Sometimes had to open up privacy settings and hit "Allow Anyway."). After running the executable a number of times it finally opened settings in safari and I was able to add a library (on a mounted external drive, if that's important) and make an account/login. Jellyfin seemed to get stuck while indexing my book library so I waited a bit and then closed the terminal window.
After starting the executable again it automatically opened safari but I could no longer access Jellyfin, just 'localhost not found.'

I've tried both _Jellyfin for macOS 10.4.3_ and _Jellyfin for macOS 10.4.3 - Phoenix Edition_. They are both much easier to install but I have the same 'localhost not found' issue. Interestingly neither of these two have auto-opened a browser.

I wonder if there are some conflicting files from different versions, but it is hard to tell as there is no uninstall option. I have tried deleting ~/Library/Application Support/jellyfin to let it regenerate but that doesn't seem to have changed anything.

**Comment by anthonylavado** [comment]
Okay, so here’s the short version:
* core signing and hardened runtime has been enforced by Apple since Feb 3rd
* this means that without proper signing and settings, regular apps won’t run
* it’s harder to do for this app since there’s about 400 resource files involved
* I got very close, but was still missing a few permissions

---

* it was working prior to Feb 3rd, and we haven’t changed the text on the website because I thought I would have had it by now
* I have spent more time than I’d like to admit working on this
* I have what I think to be the last piece of the puzzle, but I’ve been very busy lately. I’m trying again today.

---

* You can manually run the executable but have to install FFmpeg yourself and also approve all of them (not fun)
* You could disable GateKeeper, but I don’t recommend that unless you know what you’re getting in to

---

* The browser won't open unless the server runs
* The server is likely not running/running correctly, which is why you're getting console errors and "localhost not found"
* the log folders don't exist until created by the server, which hasn't started successfully in most cases

---

**Things I've done recently to fix this (but not published yet):**
* fixed an oversized menu bar icon issue
* Identified a full list of all files that must Be signed to run the app
* Scripted more running steps
* fixed the issue where the preferences window won't open
* fixed a file mismatch issue
* updated the version used and the FFmpeg used as well
* added the AppleScript event entitlement to hopefully launch the server in the background
* added a parameter to track installed server version

---

**Things I still need to do:**

* test a version with this enhanced signing and entitlement
* Figure out a way to handle updates (right now if you use the app, it won't update the version in the app support folder if it exists

**Comment by babyfish21** [comment]
same question!
waiting for your new version.

**Comment by anthonylavado** [comment]
@babyfish21 It's almost done. It's going to be a lot simpler to start.

**Comment by anthonylavado** [comment]
All, there's a release now. Please try it and follow the instructions carefully.

**Comment by babyfish21** [comment]
@anthonylavado Thank you very much. The newest version works for me.
