### ISSUE TITLE
Manual Uninstall

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-server-macos#41]
Hi Anthony, I’ve had to uninstall due to issues with android tv app. Which files do I need to delete that adding app to trash doesn’t delete.
Cheers

_Originally posted by @brabs27 in https://github.com/jellyfin/jellyfin-server-macos/issues/36#issuecomment-643842691_

**Comment by anthonylavado** [comment]
Hi @brabs27, I've just made a separate issue for this.

You can run this in a terminal, or go to these folders in the Finder:
```
rm -Rfv ~/.config/jellyfin
rm -Rfv ~/.cache/jellyfin
rm -Rfv ~/.local/share/jellyfin
```

They're hidden folders by default on macOS, if you want to do it manually, you'll need to use the Go menu in the Finder to do so.

**Comment by brabs27** [comment]
Thanks Anthony, that did the trick!

**Comment by jonyskids** [comment]
So, I did this step and reinstall jellyfin and when I open my server instance is there and all my profile setting?

Hoping to do a clean reinstall.

I think I have a corrupted hard drive so that jellyfin fails when trying to scan the libraries. My thought was to reinstall and then add one library at a time to she what is the issue.
